blueprint:
  name: Adaptive Lighting → Inovelli Blue + Z2M Group (Script)
  description: >
    Create an AL script with three inputs:
    1) Adaptive Lighting switch (fallback source for brightness/color),
    2) Inovelli Zigbee2MQTT /set topic,
    3) Zigbee2MQTT group /set topic.
  domain: script
  input:
    al_switch:
      name: Adaptive Lighting switch (fallback source)
      description: Switch entity providing brightness_pct & color_temp_kelvin attributes
      selector:
        entity:
          domain: switch
    inovelli_set_topic:
      name: Inovelli Zigbee2MQTT /set topic
      description: e.g. "zigbee2mqtt/Primary Bedroom Overhead Light Switch/set"
      selector:
        text:
    group_set_topic:
      name: Zigbee2MQTT group /set topic
      description: e.g. "zigbee2mqtt/zgb_primary_bedroom/set"
      selector:
        text:

# ---------- Script body (logic unchanged except for the three inputs) ----------
alias: AL Bedroom Overhead
mode: single
fields:
  target_state:
    description: "\"ON\" or \"OFF\" (required)"
    example: "ON"
  brightness_pct:
    description: Optional brightness percent (0–100). Falls back to AL dummy switch.
    example: 72
  color_temp_kelvin:
    description: Optional color temp in Kelvin. Falls back to AL dummy switch.
    example: 2700
sequence:
  - variables:
      # Blueprint inputs
      al_sw: !input al_switch

      pct: >-
        {% set p = brightness_pct | default(None) %}
        {% if p is number %}{{ p | int }}
        {% else %}{{ state_attr(al_sw,'brightness_pct') | int(50) }}
        {% endif %}
      kelvin: >-
        {% set k = color_temp_kelvin | default(None) %}
        {% if k is number %}{{ k | float }}
        {% else %}{{ state_attr(al_sw,'color_temp_kelvin') | float(2700) }}
        {% endif %}
      bri_raw: "{{ (pct * 254 / 100) | round(0) | int }}"
      bri: "{{ [ [ bri_raw, 1 ] | max, 254 ] | min }}"
      mired_raw: "{{ (1000000 / kelvin) | round(0) | int }}"
      mired: "{{ [ [ mired_raw, 153 ] | max, 500 ] | min }}"
      target_state_norm: "{{ target_state | upper }}"
  - action: mqtt.publish
    data:
      topic: !input inovelli_set_topic
      qos: 0
      retain: false
      payload: |-
        {{
          {
            "level_config": {"execute_if_off": true},
            "defaultLevelLocal": bri,
            "defaultLevelRemote": bri,
            "brightness": bri,
            "state": target_state_norm
          } | tojson
        }}
  - delay: "00:00:01"
  - action: mqtt.publish
    data:
      topic: !input group_set_topic
      qos: 0
      retain: false
      payload: |-
        {{
          {
            "state": target_state_norm,
            "level_config": {"execute_if_off": true},
            "color_options": {"execute_if_off": true},
            "brightness": bri,
            "color_temp": mired
          } | tojson
        }}
description: ""
