blueprint:
  name: "Ataraxia Lighting – Master Tick Automation (v0.3)"
  description: >
    Master timer tick that fans out to 11 areas. For each area, reads
    brightness_pct and color_temp_kelvin from that area's Adaptive Lighting
    dummy switch, determines ON/OFF from the area's light state, and calls the
    area's script. Includes a global stagger delay and an optional transition
    (defaults empty) passed to each script.
  domain: automation
  author: mnestrud
  source_url: https://raw.githubusercontent.com/mnestrud/ha_random/main/AL_Tick_Automation_Blueprint.yaml

  input:
    timer_entity:
      name: "Timer"
      description: "Restarted each tick to pace the cadence"
      selector:
        entity:
          domain: timer

    z2m_bridge:
      name: "Zigbee2MQTT Bridge Online Sensor"
      selector:
        entity:
          domain: binary_sensor

    per_area_delay:
      name: "Per-area stagger (seconds)"
      default: 4
      selector:
        number:
          min: 0
          max: 60
          step: 1
          mode: slider

    transition:
      name: "Transition (seconds) – optional"
      description: "Leave empty to skip (scripts should treat empty as no transition)"
      default: ""
      selector:
        text: {}

    # ------- 11 area blocks -------
    a1_enable:
      name: "Area 1 – Enable boolean"
      selector: { entity: { domain: input_boolean } }
    a1_light:
      name: "Area 1 – Light entity"
      selector: { entity: { domain: light } }
    a1_script:
      name: "Area 1 – Script to call"
      selector: { entity: { domain: script } }
    a1_al_switch:
      name: "Area 1 – AL dummy switch"
      selector: { entity: { domain: switch } }

    a2_enable:
      name: "Area 2 – Enable boolean"
      selector: { entity: { domain: input_boolean } }
    a2_light:
      name: "Area 2 – Light entity"
      selector: { entity: { domain: light } }
    a2_script:
      name: "Area 2 – Script to call"
      selector: { entity: { domain: script } }
    a2_al_switch:
      name: "Area 2 – AL dummy switch"
      selector: { entity: { domain: switch } }

    a3_enable:
      name: "Area 3 – Enable boolean"
      selector: { entity: { domain: input_boolean } }
    a3_light:
      name: "Area 3 – Light entity"
      selector: { entity: { domain: light } }
    a3_script:
      name: "Area 3 – Script to call"
      selector: { entity: { domain: script } }
    a3_al_switch:
      name: "Area 3 – AL dummy switch"
      selector: { entity: { domain: switch } }

    a4_enable:
      name: "Area 4 – Enable boolean"
      selector: { entity: { domain: input_boolean } }
    a4_light:
      name: "Area 4 – Light entity"
      selector: { entity: { domain: light } }
    a4_script:
      name: "Area 4 – Script to call"
      selector: { entity: { domain: script } }
    a4_al_switch:
      name: "Area 4 – AL dummy switch"
      selector: { entity: { domain: switch } }

    a5_enable:
      name: "Area 5 – Enable boolean"
      selector: { entity: { domain: input_boolean } }
    a5_light:
      name: "Area 5 – Light entity"
      selector: { entity: { domain: light } }
    a5_script:
      name: "Area 5 – Script to call"
      selector: { entity: { domain: script } }
    a5_al_switch:
      name: "Area 5 – AL dummy switch"
      selector: { entity: { domain: switch } }

    a6_enable:
      name: "Area 6 – Enable boolean"
      selector: { entity: { domain: input_boolean } }
    a6_light:
      name: "Area 6 – Light entity"
      selector: { entity: { domain: light } }
    a6_script:
      name: "Area 6 – Script to call"
      selector: { entity: { domain: script } }
    a6_al_switch:
      name: "Area 6 – AL dummy switch"
      selector: { entity: { domain: switch } }

    a7_enable:
      name: "Area 7 – Enable boolean"
      selector: { entity: { domain: input_boolean } }
    a7_light:
      name: "Area 7 – Light entity"
      selector: { entity: { domain: light } }
    a7_script:
      name: "Area 7 – Script to call"
      selector: { entity: { domain: script } }
    a7_al_switch:
      name: "Area 7 – AL dummy switch"
      selector: { entity: { domain: switch } }

    a8_enable:
      name: "Area 8 – Enable boolean"
      selector: { entity: { domain: input_boolean } }
    a8_light:
      name: "Area 8 – Light entity"
      selector: { entity: { domain: light } }
    a8_script:
      name: "Area 8 – Script to call"
      selector: { entity: { domain: script } }
    a8_al_switch:
      name: "Area 8 – AL dummy switch"
      selector: { entity: { domain: switch } }

    a9_enable:
      name: "Area 9 – Enable boolean"
      selector: { entity: { domain: input_boolean } }
    a9_light:
      name: "Area 9 – Light entity"
      selector: { entity: { domain: light } }
    a9_script:
      name: "Area 9 – Script to call"
      selector: { entity: { domain: script } }
    a9_al_switch:
      name: "Area 9 – AL dummy switch"
      selector: { entity: { domain: switch } }

    a10_enable:
      name: "Area 10 – Enable boolean"
      selector: { entity: { domain: input_boolean } }
    a10_light:
      name: "Area 10 – Light entity"
      selector: { entity: { domain: light } }
    a10_script:
      name: "Area 10 – Script to call"
      selector: { entity: { domain: script } }
    a10_al_switch:
      name: "Area 10 – AL dummy switch"
      selector: { entity: { domain: switch } }

    a11_enable:
      name: "Area 11 – Enable boolean"
      selector: { entity: { domain: input_boolean } }
    a11_light:
      name: "Area 11 – Light entity"
      selector: { entity: { domain: light } }
    a11_script:
      name: "Area 11 – Script to call"
      selector: { entity: { domain: script } }
    a11_al_switch:
      name: "Area 11 – AL dummy switch"
      selector: { entity: { domain: switch } }

mode: single
max_exceeded: silent

triggers:
  - trigger: event
    event_type: timer.finished
    event_data:
      entity_id: !input timer_entity
    id: TICK
  - trigger: homeassistant
    event: start
    id: START

conditions: []

actions:
  - choose:
      - conditions:
          - condition: trigger
            id: START
        sequence:
          - action: timer.start
            target:
              entity_id: !input timer_entity

      - conditions:
          - condition: trigger
            id: TICK
        sequence:
          - condition: state
            entity_id: !input z2m_bridge
            state: "on"

          - variables:
              _stagger: !input per_area_delay
              _transition: !input transition
              areas:
                - enable: !input a1_enable
                  light: !input a1_light
                  script: !input a1_script
                  al_switch: !input a1_al_switch
                - enable: !input a2_enable
                  light: !input a2_light
                  script: !input a2_script
                  al_switch: !input a2_al_switch
                - enable: !input a3_enable
                  light: !input a3_light
                  script: !input a3_script
                  al_switch: !input a3_al_switch
                - enable: !input a4_enable
                  light: !input a4_light
                  script: !input a4_script
                  al_switch: !input a4_al_switch
                - enable: !input a5_enable
                  light: !input a5_light
                  script: !input a5_script
                  al_switch: !input a5_al_switch
                - enable: !input a6_enable
                  light: !input a6_light
                  script: !input a6_script
                  al_switch: !input a6_al_switch
                - enable: !input a7_enable
                  light: !input a7_light
                  script: !input a7_script
                  al_switch: !input a7_al_switch
                - enable: !input a8_enable
                  light: !input a8_light
                  script: !input a8_script
                  al_switch: !input a8_al_switch
                - enable: !input a9_enable
                  light: !input a9_light
                  script: !input a9_script
                  al_switch: !input a9_al_switch
                - enable: !input a10_enable
                  light: !input a10_light
                  script: !input a10_script
                  al_switch: !input a10_al_switch
                - enable: !input a11_enable
                  light: !input a11_light
                  script: !input a11_script
                  al_switch: !input a11_al_switch

          - repeat:
              for_each: "{{ areas }}"
              sequence:
                - condition: template
                  value_template: >
                    {{ repeat.item.enable is not none and
                       repeat.item.light  is not none and
                       repeat.item.script is not none and
                       repeat.item.al_switch is not none and
                       is_state(repeat.item.enable, 'on') }}

                - variables:
                    _is_on: "{{ is_state(repeat.item.light, 'on') }}"
                    _target_state: "{{ 'ON' if _is_on else 'OFF' }}"
                    _bri_pct: "{{ state_attr(repeat.item.al_switch, 'brightness_pct') | int(50) }}"
                    _kelvin:  "{{ state_attr(repeat.item.al_switch, 'color_temp_kelvin') | float(2700) }}"

                - action: script.turn_on
                  target:
                    entity_id: "{{ repeat.item.script }}"
                  data:
                    variables:
                      target_state: "{{ _target_state }}"
                      brightness_pct: "{{ _bri_pct }}"
                      color_temp_kelvin: "{{ _kelvin }}"
                      transition: "{{ _transition }}"

                - delay:
                    seconds: "{{ _stagger | int(0) }}"

          - action: timer.start
            target:
              entity_id: !input timer_entity
